(TeX-add-style-hook "Main"
 (lambda ()
    (LaTeX-add-bibliographies
     "my.bib")
    (LaTeX-add-labels
     "Bibliography")
    (TeX-add-symbols
     "HRule")
    (TeX-run-style-hooks
     "mypack"
     "natbib"
     "square"
     "numbers"
     "comma"
     "sort&compress"
     "diagxy"
     "proof"
     "booktabs"
     "xspace"
     "inputenc"
     "utf8x"
     "textgreek"
     "stmaryrd"
     "autofe"
     "amssymb"
     "amsfonts"
     "amsmath"
     "color"
     "relsize"
     "amsthm"
     "dsfont"
     "agda"
     "xy"
     "matrix"
     "latex2e"
     "Thesis11"
     "Thesis"
     "11pt"
     "a4paper"
     "UKenglish"
     "twoside"
     "openright"
     "Chapters/Introduction"
     "Chapters/Background"
     "Chapters/QuotientTypes"
     "Chapters/DefinableQuotients"
     "Chapters/SetoidModel"
     "Chapters/OGModel"
     "Chapters/Summary")))

