(TeX-add-style-hook "talk_away"
 (lambda ()
    (TeX-run-style-hooks
     "textpos"
     "absolute"
     "overlay"
     "quiet"
     "apacite"
     "nobibnewpage"
     "notocbib"
     "booktabs"
     "proof"
     "xy"
     "all"
     "multimedia"
     "babel"
     "english"
     "color"
     "graphicx"
     "stmaryrd"
     "amssymb"
     "amsmath"
     "ifthen"
     "xspace"
     "inputenc"
     "latin1"
     "etex"
     "latex2e"
     "beamer12"
     "beamer"
     "12pt"
     "pdflatex"
     "t"
     "handout")))

