(TeX-add-style-hook "slides"
 (lambda ()
    (LaTeX-add-environments
     '("colorblock" 2))
    (TeX-run-style-hooks
     "semantic"
     "inference"
     "fancybox"
     "cmbright"
     "fontenc"
     "T1"
     "textpos"
     "absolute"
     "overlay"
     "quiet"
     "apacite"
     "nobibnewpage"
     "notocbib"
     "booktabs"
     "xy"
     "all"
     "animate"
     "multimedia"
     "graphicx"
     "babel"
     "english"
     "proof"
     "stmaryrd"
     "amssymb"
     "amsmath"
     "ifthen"
     "xspace"
     "textgreek"
     "autofe"
     "relsize"
     "inputenc"
     "utf8x"
     "ucs"
     "mypack"
     "agda"
     "etex"
     "latex2e"
     "beamer12"
     "beamer"
     "12pt"
     "mathserif"
     "handout")))

